{{-- resources/views/admin/admin-reports.blade.php --}}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>Admin • Reports & Logs · NurSync</title>
      <link rel="icon" type="image/x-icon" href="{{ asset('CON_LOGO.ico') }}">
    <link rel="shortcut icon" type="image/x-icon" href="{{ asset('CON_LOGO.ico') }}">
  @vite(['resources/css/app.css', 'resources/js/app.js'])
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style> body { font-family: 'Poppins', ui-sans-serif, system-ui, sans-serif; } </style>
</head>
<body class="min-h-screen bg-slate-50">

  <main class="min-h-screen flex">
    {{-- Sidebar --}}
    @include('partials.admin-sidebar', ['active' => 'reports'])

    {{-- Main --}}
    <section class="flex-1 min-w-0">
      {{-- Header --}}
      <header class="sticky top-0 z-30 bg-white/80 backdrop-blur border-b border-slate-200">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <div class="flex items-center gap-3">
            <div class="inline-flex h-8 w-8 items-center justify-center rounded-xl bg-slate-900 text-white shadow-sm">
              <i data-lucide="file-text" class="h-4 w-4"></i>
            </div>
            <div>
              <h1 class="text-[15px] sm:text-[16px] font-semibold leading-tight">Reports & Logs</h1>
              <p class="text-[12px] text-slate-500 -mt-0.5">View system reports, activity logs, and exports.</p>
            </div>
          </div>

          {{-- Primary action --}}
          <div class="flex items-center gap-2">
            <button type="button"
              class="inline-flex items-center gap-2 rounded-xl bg-green-600 text-white px-3 py-2 text-[13px] font-medium shadow hover:bg-green-700 active:scale-[.99]"
              data-modal-target="modalGenerate">
              <i data-lucide="plus" class="h-4 w-4"></i>
              <span>Generate Report</span>
            </button>
          </div>
        </div>
      </header>

      {{-- Content --}}
      <div class="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-6">

        {{-- Filters --}}
        <div class="bg-white rounded-2xl border border-slate-200 shadow-sm p-4">
          <div class="flex flex-col sm:flex-row gap-3 sm:items-center sm:justify-between">
            <div class="flex items-center gap-3 w-full sm:w-auto">
              <div class="relative flex-1 sm:w-72">
                <i data-lucide="search" class="absolute left-3 top-2.5 h-4 w-4 text-slate-400"></i>
                <input type="text" placeholder="Search report name or type..."
                       class="w-full rounded-xl border-slate-200 pl-9 pr-3 py-2.5 text-sm focus:ring-2 focus:ring-slate-300">
              </div>

              <select class="rounded-xl border-slate-200 text-sm py-2.5 px-3 focus:ring-2 focus:ring-slate-300">
                <option value="">All types</option>
                <option>Audit Logs</option>
                <option>Attendance</option>
                <option>Duty Reports</option>
                <option>Return Demo</option>
              </select>

              <input type="date" class="rounded-xl border-slate-200 text-sm py-2.5 px-3 focus:ring-2 focus:ring-slate-300">
            </div>
          </div>
        </div>

        {{-- Table --}}
        <div class="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <div class="overflow-x-auto">
            <table class="min-w-full text-sm">
              <thead class="bg-slate-50 border-b border-slate-200">
                <tr class="text-left text-slate-600">
                  <th class="px-4 py-3">Report Name</th>
                  <th class="px-4 py-3">Type</th>
                  <th class="px-4 py-3">Generated</th>
                  <th class="px-4 py-3">Generated By</th>
                  <th class="px-4 py-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-slate-200">
                {{-- Row 1 --}}
                <tr class="hover:bg-slate-50">
                  <td class="px-4 py-3 font-medium text-slate-900">September Duty Attendance</td>
                  <td class="px-4 py-3 text-slate-700">Attendance</td>
                  <td class="px-4 py-3 text-slate-700">Sep 25, 2025</td>
                  <td class="px-4 py-3 text-slate-700">Admin</td>
                  <td class="px-4 py-3">
                    <div class="flex items-center justify-end gap-1.5">
                      <button type="button" class="inline-flex items-center justify-center rounded-lg bg-blue-600 text-white p-2 hover:bg-blue-700" data-modal-target="modalView">
                        <i data-lucide="eye" class="h-4 w-4"></i>
                      </button>
                      <button type="button" class="inline-flex items-center justify-center rounded-lg bg-indigo-600 text-white p-2 hover:bg-indigo-700">
                        <i data-lucide="download" class="h-4 w-4"></i>
                      </button>
                      <button type="button" class="inline-flex items-center justify-center rounded-lg bg-red-600 text-white p-2 hover:bg-red-700" data-modal-target="modalDelete">
                        <i data-lucide="trash-2" class="h-4 w-4"></i>
                      </button>
                    </div>
                  </td>
                </tr>

                {{-- Row 2 --}}
                <tr class="hover:bg-slate-50">
                  <td class="px-4 py-3 font-medium text-slate-900">Audit Log — Faculty Approvals</td>
                  <td class="px-4 py-3 text-slate-700">Audit Logs</td>
                  <td class="px-4 py-3 text-slate-700">Sep 24, 2025</td>
                  <td class="px-4 py-3 text-slate-700">System</td>
                  <td class="px-4 py-3">
                    <div class="flex items-center justify-end gap-1.5">
                      <button type="button" class="inline-flex items-center justify-center rounded-lg bg-blue-600 text-white p-2 hover:bg-blue-700" data-modal-target="modalView">
                        <i data-lucide="eye" class="h-4 w-4"></i>
                      </button>
                      <button type="button" class="inline-flex items-center justify-center rounded-lg bg-indigo-600 text-white p-2 hover:bg-indigo-700">
                        <i data-lucide="download" class="h-4 w-4"></i>
                      </button>
                      <button type="button" class="inline-flex items-center justify-center rounded-lg bg-red-600 text-white p-2 hover:bg-red-700" data-modal-target="modalDelete">
                        <i data-lucide="trash-2" class="h-4 w-4"></i>
                      </button>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </section>
  </main>

  {{-- Shared footer --}}
  @include('partials.admin-footer')

  {{-- Generate Report Modal --}}
  <div id="modalGenerate" class="hidden fixed inset-0 z-50">
    <div class="absolute inset-0 bg-black/40"></div>
    <div class="relative mx-auto mt-24 w-full max-w-lg">
      <div class="bg-white rounded-2xl shadow-xl border border-slate-200 p-5">
        <div class="flex items-center justify-between">
          <h3 class="text-[15px] font-semibold">Generate Report</h3>
          <button class="p-2 rounded-lg hover:bg-slate-100" data-modal-close>
            <i data-lucide="x" class="h-5 w-5"></i>
          </button>
        </div>
        <div class="mt-4 space-y-3">
          <div>
            <label class="text-[12px] text-slate-600">Report Type</label>
            <select class="mt-1 w-full rounded-xl border-slate-200 px-3 py-2.5 text-sm">
              <option>Attendance</option>
              <option>Audit Logs</option>
              <option>Duty Reports</option>
              <option>Return Demo</option>
            </select>
          </div>
          <div>
            <label class="text-[12px] text-slate-600">Date Range</label>
            <input type="date" class="mt-1 w-full rounded-xl border-slate-200 px-3 py-2.5 text-sm">
          </div>
        </div>
        <div class="mt-5 flex items-center justify-end gap-2">
          <button class="px-3 py-2 rounded-xl text-[13px] border border-slate-200 bg-white hover:bg-slate-50" data-modal-close>Cancel</button>
          <button class="px-3 py-2 rounded-xl text-[13px] bg-green-600 text-white hover:bg-green-700 inline-flex items-center gap-2">
            <i data-lucide="check" class="h-4 w-4"></i> Generate
          </button>
        </div>
      </div>
    </div>
  </div>

  {{-- Icons + modal toggles --}}
  <script src="https://unpkg.com/lucide@latest"></script>
  <script>
    lucide.createIcons();
    document.querySelectorAll('[data-modal-target]').forEach(btn => {
      btn.addEventListener('click', () => {
        const id = btn.getAttribute('data-modal-target');
        document.getElementById(id)?.classList.remove('hidden');
        lucide.createIcons();
      });
    });
    document.querySelectorAll('[data-modal-close]').forEach(btn => {
      btn.addEventListener('click', () => btn.closest('.fixed.inset-0')?.classList.add('hidden'));
    });
    document.querySelectorAll('.fixed.inset-0').forEach(modal => {
      modal.addEventListener('click', (e) => { if (e.target === modal) modal.classList.add('hidden'); });
    });
  </script>
</body>
</html>
